# Generated by Django 4.1.4 on 2022-12-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemTitle', models.CharField(max_length=255)),
                ('itemDescription', models.CharField(max_length=255)),
                ('itemStartPrice', models.IntegerField()),
                ('itemPicture', models.ImageField(upload_to='')),
                ('itemFinishDate', models.DateField(verbose_name='Finish Date')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidAmount', models.IntegerField()),
            ],
        ),
    ]
