# Generated by Django 4.1.3 on 2022-12-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionApp', '0003_remove_customuser_userpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='itemPicture',
            field=models.URLField(max_length=128),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userImage',
            field=models.URLField(max_length=128),
        ),
    ]
