# Generated by Django 4.1.2 on 2022-12-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionApp', '0004_alter_auction_itempicture_alter_customuser_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='itemPicture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userImage',
            field=models.URLField(),
        ),
    ]
