# Generated by Django 3.2.5 on 2022-12-18 18:57

import auctionApp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctionApp', '0006_alter_auction_itempicture_alter_customuser_userimage'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', auctionApp.models.MyUserManager()),
            ],
        ),
    ]
