# Generated by Django 4.1.3 on 2022-12-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionApp', '0009_alter_customuser_managers_alter_profile_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userImage',
            field=models.ImageField(default='mainapp/frontend/src/assets/default-profile.png', upload_to='mainApp/frontend/src/assets'),
        ),
    ]
